# Generated by Django 2.2.5 on 2019-10-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
