# Generated by Django 2.2.5 on 2019-11-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191008_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=40)),
                ('employee_number', models.CharField(max_length=10)),
                ('store_name', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='E_user',
        ),
        migrations.DeleteModel(
            name='store',
        ),
    ]
