# Generated by Django 2.2.5 on 2019-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20191106_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
