# Generated by Django 2.2.5 on 2019-11-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_drugs_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=5)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
