# Generated by Django 2.2.5 on 2019-11-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_loadmeter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoadMeter',
            new_name='Meters',
        ),
    ]
