# Generated by Django 2.2.5 on 2019-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20191118_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SensorID', models.CharField(max_length=100)),
                ('Date_n_Time', models.DateField(auto_now_add=True, null=True)),
                ('Temperature', models.CharField(max_length=50)),
            ],
        ),
    ]
