# Generated by Django 2.2.5 on 2019-11-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_temperature_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('house_no', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.Client_data')),
            ],
        ),
        migrations.CreateModel(
            name='Meter_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=5)),
                ('quantity', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Meter')),
            ],
        ),
        migrations.DeleteModel(
            name='drugs',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='Meters',
        ),
        migrations.DeleteModel(
            name='Temperature_Data',
        ),
    ]
