# Generated by Django 2.2.5 on 2019-11-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20191122_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='house_no',
        ),
        migrations.DeleteModel(
            name='Client_data',
        ),
    ]
