# Generated by Django 2.2.5 on 2019-11-25 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_meter_house_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='house_no',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='meter_action',
            name='quantity',
        ),
        migrations.CreateModel(
            name='load_meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Meter')),
            ],
        ),
    ]
