# Generated by Django 2.2.5 on 2019-12-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20191125_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.FloatField(default=0)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Meter')),
            ],
        ),
    ]
