# Generated by Django 2.2.5 on 2019-12-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_daily_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_consumption',
            name='usage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='load_meter',
            name='quantity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='balance',
            field=models.FloatField(blank=True),
        ),
    ]
