# Generated by Django 2.2.5 on 2019-12-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20191208_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_consumption',
        ),
    ]
