# Generated by Django 2.2.5 on 2019-12-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_daily_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_meter',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meter',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='daily_consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.FloatField(default=0)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Meter')),
            ],
        ),
    ]
