# Generated by Django 2.2.5 on 2019-12-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20191208_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_consumption',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
