# Generated by Django 2.2.5 on 2019-12-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20191216_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load_meter',
            old_name='quantity',
            new_name='units',
        ),
        migrations.AddField(
            model_name='load_meter',
            name='ksh',
            field=models.FloatField(default=0),
        ),
    ]
