# Generated by Django 2.2.5 on 2019-12-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_meter_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load_meter',
            old_name='time',
            new_name='day',
        ),
    ]
