# Generated by Django 2.2.5 on 2019-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20191226_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_meter',
            name='day',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
