# Generated by Django 2.2.5 on 2020-01-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20191227_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_meter',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
