# Generated by Django 2.2.5 on 2020-01-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20200101_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meter_action',
        ),
    ]
