# Generated by Django 2.2.5 on 2020-01-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_delete_meter_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_consumption',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
