# Generated by Django 2.2.5 on 2020-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20200107_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_meter',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
