# Generated by Django 2.2.5 on 2020-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_meter_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_meter',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
