# Generated by Django 2.2.5 on 2020-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20200425_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_meter',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
